### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by jdfreder**
It's a start..

### CODE REVIEW

**Comment by jdfreder** [comment]
The base model should now support hierarchies of models, including events and serialization.

**Comment by jdfreder** [comment]
@dwillmer , @sccolbert said that you may have used the code from this PR.  I just wanted to give you a heads up - I'm going to rename some of the classes here and add an interchangeable model layer.  I'll pingback once I've done that.

**Comment by sccolbert** [comment]
@blink1073 is the relevant user

**Comment by blink1073** [comment]
Thanks for the heads up, I ended up using the existing notebook code for the input area in the demo.

**Comment by jdfreder** [comment]
Ah, sorry @blink1073 .  That's what I thought, this isn't ready to be used anyways.  I was surprised when Chris said he thought you were using this.

**Comment by sccolbert** [comment]
Whoops, my bad. Sorry for the misinformation.

**Comment by jdfreder** [comment]
@jasongrout, @ellisonbg said you are interested in working on this.  

Right now I've written the view base classes, CodeMirror implementation, and the model base class - all with mocha tests.  Still TODO:

Implement single user model
Implement multi-user model
Declare properties at the class level and proxy to instance methods
Readme, Docs, and Demos

**Pull request merged**
